name: Picoware CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./picoware

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      - name: Arduino CLI Core Index Update
        run: |
          arduino-cli config init
          arduino-cli core update-index

      - name: Arduino RP2040 Platform Installation
        run: arduino-cli core install rp2040:rp2040 --additional-urls https://github.com/earlephilhower/arduino-pico/releases/download/global/package_rp2040_index.json

      - name: Picoware for RP2040
        run: |
          arduino-cli compile --fqbn rp2040:rp2040:rpipico:opt=Optimize3 picoware.ino
